apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-resource-monitor
  labels:
    app: system-resource-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-resource-monitor
  template:
    metadata:
      labels:
        app: system-resource-monitor
    spec:
      containers:
        - name: api
          image: system-resource-monitor:local
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /v1/readyz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: system-resource-monitor
spec:
  selector:
    app: system-resource-monitor
  ports:
    - port: 80
      targetPort: 8080
